version: '3.8'

services:

  server:
    image: durru/server:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      main-network:
        ipv4_address: 192.168.0.10
    restart: always

  db:
    image: durru/db:1.0
    environment:
      MYSQL_ROOT_PASSWORD: m4nd4l0r14n0
      MYSQL_DATABASE: db_easyflight
    volumes:
      - db_data:/var/lib/mysql
    networks:
      main-network:
    restart: always

  scrapi:
    image: durru/scrapi:1.0
    networks:
      main-network:
      proxy-network:
    depends_on:
      - server
    restart: always
  
  proxy:
    image: durru/proxy:1.0
    networks:
      proxy-network:
    restart: always

networks:
  main-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  proxy-network:
    driver: bridge

volumes:
  db_data:
